### PR TITLE
Allow Greek letters in Id lexer

### PR DESCRIPTION
**Pull request by jacbn**
Allows Α-Ω, α-ω in Id pattern matching

### CODE REVIEW

**Comment by Morpheu5** [comment]
There's a reserved character at U03AB which shouldn't be included in the range, otherwise LGTM.

**Comment by jsharkey13** [comment]
I don't think so?
```javascript
/[a-zA-ZΑ-Ωα-ω]+/.test("\u03AB")
// false
```

**Comment by Morpheu5** [comment]
Ooops, my bad, I typed a `B` instead of a `2`. Serves me right for doing code reviews on my phone…

Anyway, the hole is [here](https://www.unicode.org/charts/PDF/U0370.pdf). It's a very minor annoyance but, you know… :)

**Comment by jsharkey13** [comment]
How did you obtain this cursed knowledge? 😳 We were just looking at character lists and missed the gap. We will fix it, thank you!

**Comment by Morpheu5** [comment]
> How did you obtain this cursed knowledge? 😳

In short, [EBCDIC](https://en.wikipedia.org/wiki/EBCDIC). It's a relatively obscure encoding from the early days of mainframes, and it seems we haven't learned very much since.

Happy to bring up cursed knowledge any way I can 😬

**Review by skyepurchase — APPROVED** [review]

**Pull request merged**
